// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Mirrors com.dyplink.sdk.internal.util.LogLevel.
enum DyplinkLogLevel: Int {
  case none = 0
  case error = 1
  case warn = 2
  case info = 3
  case debug = 4
  case verbose = 5
}

/// Flat configuration object passed to [DyplinkHostApi.init].
///
/// All fields have the same semantics as
/// `com.dyplink.sdk.DyplinkConfig.Builder`. The native side converts this
/// to a real `DyplinkConfig` via its builder so validation rules
/// (non-blank strings, positive intervals) are enforced by existing Kotlin
/// code.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DyplinkConfigDto {
  var baseUrl: String
  var apiKey: String
  var projectId: String
  var logLevel: DyplinkLogLevel
  var flushIntervalSeconds: Int64
  var maxQueueSize: Int64
  var maxRetries: Int64
  var sessionTimeoutSeconds: Int64
  var enableAutoSessionTracking: Bool
  var enableAutoDeviceInfo: Bool
  var deepLinkHosts: [String]
  var customScheme: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DyplinkConfigDto? {
    let baseUrl = pigeonVar_list[0] as! String
    let apiKey = pigeonVar_list[1] as! String
    let projectId = pigeonVar_list[2] as! String
    let logLevel = pigeonVar_list[3] as! DyplinkLogLevel
    let flushIntervalSeconds = pigeonVar_list[4] as! Int64
    let maxQueueSize = pigeonVar_list[5] as! Int64
    let maxRetries = pigeonVar_list[6] as! Int64
    let sessionTimeoutSeconds = pigeonVar_list[7] as! Int64
    let enableAutoSessionTracking = pigeonVar_list[8] as! Bool
    let enableAutoDeviceInfo = pigeonVar_list[9] as! Bool
    let deepLinkHosts = pigeonVar_list[10] as! [String]
    let customScheme: String? = nilOrValue(pigeonVar_list[11])

    return DyplinkConfigDto(
      baseUrl: baseUrl,
      apiKey: apiKey,
      projectId: projectId,
      logLevel: logLevel,
      flushIntervalSeconds: flushIntervalSeconds,
      maxQueueSize: maxQueueSize,
      maxRetries: maxRetries,
      sessionTimeoutSeconds: sessionTimeoutSeconds,
      enableAutoSessionTracking: enableAutoSessionTracking,
      enableAutoDeviceInfo: enableAutoDeviceInfo,
      deepLinkHosts: deepLinkHosts,
      customScheme: customScheme
    )
  }
  func toList() -> [Any?] {
    return [
      baseUrl,
      apiKey,
      projectId,
      logLevel,
      flushIntervalSeconds,
      maxQueueSize,
      maxRetries,
      sessionTimeoutSeconds,
      enableAutoSessionTracking,
      enableAutoDeviceInfo,
      deepLinkHosts,
      customScheme,
    ]
  }
}

/// Mirrors com.dyplink.sdk.model.IdentifyParams — flat DTO (builder lives in Dart).
///
/// Generated class from Pigeon that represents data sent in messages.
struct IdentifyParamsDto {
  var distinctId: String? = nil
  var externalUserId: String? = nil
  var firstName: String? = nil
  var lastName: String? = nil
  var phone: String? = nil
  var avatar: String? = nil
  var locale: String? = nil
  var language: String? = nil
  var appVersion: String? = nil
  var appBuild: String? = nil
  var traits: [String?: Any?]? = nil
  var utmSource: String? = nil
  var utmMedium: String? = nil
  var utmCampaign: String? = nil
  var utmContent: String? = nil
  var utmTerm: String? = nil
  var installSource: String? = nil
  var installCampaign: String? = nil
  var emailOptIn: Bool? = nil
  var smsOptIn: Bool? = nil
  var pushOptIn: Bool? = nil
  var gdprConsent: Bool? = nil
  var doNotTrack: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IdentifyParamsDto? {
    let distinctId: String? = nilOrValue(pigeonVar_list[0])
    let externalUserId: String? = nilOrValue(pigeonVar_list[1])
    let firstName: String? = nilOrValue(pigeonVar_list[2])
    let lastName: String? = nilOrValue(pigeonVar_list[3])
    let phone: String? = nilOrValue(pigeonVar_list[4])
    let avatar: String? = nilOrValue(pigeonVar_list[5])
    let locale: String? = nilOrValue(pigeonVar_list[6])
    let language: String? = nilOrValue(pigeonVar_list[7])
    let appVersion: String? = nilOrValue(pigeonVar_list[8])
    let appBuild: String? = nilOrValue(pigeonVar_list[9])
    let traits: [String?: Any?]? = nilOrValue(pigeonVar_list[10])
    let utmSource: String? = nilOrValue(pigeonVar_list[11])
    let utmMedium: String? = nilOrValue(pigeonVar_list[12])
    let utmCampaign: String? = nilOrValue(pigeonVar_list[13])
    let utmContent: String? = nilOrValue(pigeonVar_list[14])
    let utmTerm: String? = nilOrValue(pigeonVar_list[15])
    let installSource: String? = nilOrValue(pigeonVar_list[16])
    let installCampaign: String? = nilOrValue(pigeonVar_list[17])
    let emailOptIn: Bool? = nilOrValue(pigeonVar_list[18])
    let smsOptIn: Bool? = nilOrValue(pigeonVar_list[19])
    let pushOptIn: Bool? = nilOrValue(pigeonVar_list[20])
    let gdprConsent: Bool? = nilOrValue(pigeonVar_list[21])
    let doNotTrack: Bool? = nilOrValue(pigeonVar_list[22])

    return IdentifyParamsDto(
      distinctId: distinctId,
      externalUserId: externalUserId,
      firstName: firstName,
      lastName: lastName,
      phone: phone,
      avatar: avatar,
      locale: locale,
      language: language,
      appVersion: appVersion,
      appBuild: appBuild,
      traits: traits,
      utmSource: utmSource,
      utmMedium: utmMedium,
      utmCampaign: utmCampaign,
      utmContent: utmContent,
      utmTerm: utmTerm,
      installSource: installSource,
      installCampaign: installCampaign,
      emailOptIn: emailOptIn,
      smsOptIn: smsOptIn,
      pushOptIn: pushOptIn,
      gdprConsent: gdprConsent,
      doNotTrack: doNotTrack
    )
  }
  func toList() -> [Any?] {
    return [
      distinctId,
      externalUserId,
      firstName,
      lastName,
      phone,
      avatar,
      locale,
      language,
      appVersion,
      appBuild,
      traits,
      utmSource,
      utmMedium,
      utmCampaign,
      utmContent,
      utmTerm,
      installSource,
      installCampaign,
      emailOptIn,
      smsOptIn,
      pushOptIn,
      gdprConsent,
      doNotTrack,
    ]
  }
}

/// Mirrors com.dyplink.sdk.model.IdentifyResult.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IdentifyResultDto {
  var id: String
  var projectId: String
  var distinctId: String? = nil
  var externalUserId: String? = nil
  var deviceFingerprint: String
  var platform: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IdentifyResultDto? {
    let id = pigeonVar_list[0] as! String
    let projectId = pigeonVar_list[1] as! String
    let distinctId: String? = nilOrValue(pigeonVar_list[2])
    let externalUserId: String? = nilOrValue(pigeonVar_list[3])
    let deviceFingerprint = pigeonVar_list[4] as! String
    let platform = pigeonVar_list[5] as! String

    return IdentifyResultDto(
      id: id,
      projectId: projectId,
      distinctId: distinctId,
      externalUserId: externalUserId,
      deviceFingerprint: deviceFingerprint,
      platform: platform
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      projectId,
      distinctId,
      externalUserId,
      deviceFingerprint,
      platform,
    ]
  }
}

/// Mirrors com.dyplink.sdk.model.DeepLinkResult.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeepLinkResultDto {
  var url: String
  var shortCode: String? = nil
  var params: [String?: Any?]? = nil
  var isDeferred: Bool
  var linkId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeepLinkResultDto? {
    let url = pigeonVar_list[0] as! String
    let shortCode: String? = nilOrValue(pigeonVar_list[1])
    let params: [String?: Any?]? = nilOrValue(pigeonVar_list[2])
    let isDeferred = pigeonVar_list[3] as! Bool
    let linkId: String? = nilOrValue(pigeonVar_list[4])

    return DeepLinkResultDto(
      url: url,
      shortCode: shortCode,
      params: params,
      isDeferred: isDeferred,
      linkId: linkId
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      shortCode,
      params,
      isDeferred,
      linkId,
    ]
  }
}

/// Mirrors com.dyplink.sdk.model.DeferredMatchResult.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeferredMatchResultDto {
  var matched: Bool
  var linkId: String? = nil
  var shortCode: String? = nil
  var params: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeferredMatchResultDto? {
    let matched = pigeonVar_list[0] as! Bool
    let linkId: String? = nilOrValue(pigeonVar_list[1])
    let shortCode: String? = nilOrValue(pigeonVar_list[2])
    let params: [String?: Any?]? = nilOrValue(pigeonVar_list[3])

    return DeferredMatchResultDto(
      matched: matched,
      linkId: linkId,
      shortCode: shortCode,
      params: params
    )
  }
  func toList() -> [Any?] {
    return [
      matched,
      linkId,
      shortCode,
      params,
    ]
  }
}

/// Mirrors com.dyplink.sdk.model.TrackConversionParams.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TrackConversionParamsDto {
  var eventType: String
  var shortCode: String? = nil
  var linkId: String? = nil
  var externalUserId: String? = nil
  var metadata: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackConversionParamsDto? {
    let eventType = pigeonVar_list[0] as! String
    let shortCode: String? = nilOrValue(pigeonVar_list[1])
    let linkId: String? = nilOrValue(pigeonVar_list[2])
    let externalUserId: String? = nilOrValue(pigeonVar_list[3])
    let metadata: [String?: Any?]? = nilOrValue(pigeonVar_list[4])

    return TrackConversionParamsDto(
      eventType: eventType,
      shortCode: shortCode,
      linkId: linkId,
      externalUserId: externalUserId,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      eventType,
      shortCode,
      linkId,
      externalUserId,
      metadata,
    ]
  }
}

/// Mirrors com.dyplink.banners.model.Banner.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BannerDto {
  var id: String
  var title: String
  var imageUrl: String? = nil
  var clickUrl: String? = nil
  var ctaText: String? = nil
  var sortOrder: Int64
  var isActive: Bool
  var metadata: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerDto? {
    let id = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let imageUrl: String? = nilOrValue(pigeonVar_list[2])
    let clickUrl: String? = nilOrValue(pigeonVar_list[3])
    let ctaText: String? = nilOrValue(pigeonVar_list[4])
    let sortOrder = pigeonVar_list[5] as! Int64
    let isActive = pigeonVar_list[6] as! Bool
    let metadata: [String?: Any?]? = nilOrValue(pigeonVar_list[7])

    return BannerDto(
      id: id,
      title: title,
      imageUrl: imageUrl,
      clickUrl: clickUrl,
      ctaText: ctaText,
      sortOrder: sortOrder,
      isActive: isActive,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      imageUrl,
      clickUrl,
      ctaText,
      sortOrder,
      isActive,
      metadata,
    ]
  }
}

/// Mirrors com.dyplink.banners.model.BannerCategory.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BannerCategoryDto {
  var id: String
  var name: String
  var layout: String
  var aspectRatio: String? = nil
  var autoRotate: Bool
  var rotationInterval: Int64
  var heading: String? = nil
  var backgroundColor: String
  var padding: Int64
  var banners: [BannerDto?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerCategoryDto? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let layout = pigeonVar_list[2] as! String
    let aspectRatio: String? = nilOrValue(pigeonVar_list[3])
    let autoRotate = pigeonVar_list[4] as! Bool
    let rotationInterval = pigeonVar_list[5] as! Int64
    let heading: String? = nilOrValue(pigeonVar_list[6])
    let backgroundColor = pigeonVar_list[7] as! String
    let padding = pigeonVar_list[8] as! Int64
    let banners = pigeonVar_list[9] as! [BannerDto?]

    return BannerCategoryDto(
      id: id,
      name: name,
      layout: layout,
      aspectRatio: aspectRatio,
      autoRotate: autoRotate,
      rotationInterval: rotationInterval,
      heading: heading,
      backgroundColor: backgroundColor,
      padding: padding,
      banners: banners
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      layout,
      aspectRatio,
      autoRotate,
      rotationInterval,
      heading,
      backgroundColor,
      padding,
      banners,
    ]
  }
}

/// Mirrors com.dyplink.messages.model.MessageButton.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MessageButtonDto {
  var id: String
  var text: String
  var action: String
  var actionUrl: String? = nil
  var actionEvent: String? = nil
  var style: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageButtonDto? {
    let id = pigeonVar_list[0] as! String
    let text = pigeonVar_list[1] as! String
    let action = pigeonVar_list[2] as! String
    let actionUrl: String? = nilOrValue(pigeonVar_list[3])
    let actionEvent: String? = nilOrValue(pigeonVar_list[4])
    let style = pigeonVar_list[5] as! String

    return MessageButtonDto(
      id: id,
      text: text,
      action: action,
      actionUrl: actionUrl,
      actionEvent: actionEvent,
      style: style
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      text,
      action,
      actionUrl,
      actionEvent,
      style,
    ]
  }
}

/// Mirrors com.dyplink.messages.model.MessageTheme.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MessageThemeDto {
  var backgroundColor: String? = nil
  var textColor: String? = nil
  var titleColor: String? = nil
  var buttonPrimaryColor: String? = nil
  var buttonSecondaryColor: String? = nil
  var overlayColor: String? = nil
  var borderRadius: Int64? = nil
  var animation: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageThemeDto? {
    let backgroundColor: String? = nilOrValue(pigeonVar_list[0])
    let textColor: String? = nilOrValue(pigeonVar_list[1])
    let titleColor: String? = nilOrValue(pigeonVar_list[2])
    let buttonPrimaryColor: String? = nilOrValue(pigeonVar_list[3])
    let buttonSecondaryColor: String? = nilOrValue(pigeonVar_list[4])
    let overlayColor: String? = nilOrValue(pigeonVar_list[5])
    let borderRadius: Int64? = nilOrValue(pigeonVar_list[6])
    let animation: String? = nilOrValue(pigeonVar_list[7])

    return MessageThemeDto(
      backgroundColor: backgroundColor,
      textColor: textColor,
      titleColor: titleColor,
      buttonPrimaryColor: buttonPrimaryColor,
      buttonSecondaryColor: buttonSecondaryColor,
      overlayColor: overlayColor,
      borderRadius: borderRadius,
      animation: animation
    )
  }
  func toList() -> [Any?] {
    return [
      backgroundColor,
      textColor,
      titleColor,
      buttonPrimaryColor,
      buttonSecondaryColor,
      overlayColor,
      borderRadius,
      animation,
    ]
  }
}

/// Mirrors com.dyplink.messages.model.InAppMessage (delivered to the stream,
/// not returned from a method call).
///
/// Generated class from Pigeon that represents data sent in messages.
struct InAppMessageDto {
  var id: String
  var messageType: String
  var title: String
  var body: String? = nil
  var imageUrl: String? = nil
  var imagePosition: String
  var buttons: [MessageButtonDto?]? = nil
  var theme: MessageThemeDto? = nil
  var dismissOnTapOutside: Bool
  var autoDismissSeconds: Int64? = nil
  var triggerDelay: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InAppMessageDto? {
    let id = pigeonVar_list[0] as! String
    let messageType = pigeonVar_list[1] as! String
    let title = pigeonVar_list[2] as! String
    let body: String? = nilOrValue(pigeonVar_list[3])
    let imageUrl: String? = nilOrValue(pigeonVar_list[4])
    let imagePosition = pigeonVar_list[5] as! String
    let buttons: [MessageButtonDto?]? = nilOrValue(pigeonVar_list[6])
    let theme: MessageThemeDto? = nilOrValue(pigeonVar_list[7])
    let dismissOnTapOutside = pigeonVar_list[8] as! Bool
    let autoDismissSeconds: Int64? = nilOrValue(pigeonVar_list[9])
    let triggerDelay = pigeonVar_list[10] as! Int64

    return InAppMessageDto(
      id: id,
      messageType: messageType,
      title: title,
      body: body,
      imageUrl: imageUrl,
      imagePosition: imagePosition,
      buttons: buttons,
      theme: theme,
      dismissOnTapOutside: dismissOnTapOutside,
      autoDismissSeconds: autoDismissSeconds,
      triggerDelay: triggerDelay
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      messageType,
      title,
      body,
      imageUrl,
      imagePosition,
      buttons,
      theme,
      dismissOnTapOutside,
      autoDismissSeconds,
      triggerDelay,
    ]
  }
}

private class PigeonApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DyplinkLogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DyplinkConfigDto.fromList(self.readValue() as! [Any?])
    case 131:
      return IdentifyParamsDto.fromList(self.readValue() as! [Any?])
    case 132:
      return IdentifyResultDto.fromList(self.readValue() as! [Any?])
    case 133:
      return DeepLinkResultDto.fromList(self.readValue() as! [Any?])
    case 134:
      return DeferredMatchResultDto.fromList(self.readValue() as! [Any?])
    case 135:
      return TrackConversionParamsDto.fromList(self.readValue() as! [Any?])
    case 136:
      return BannerDto.fromList(self.readValue() as! [Any?])
    case 137:
      return BannerCategoryDto.fromList(self.readValue() as! [Any?])
    case 138:
      return MessageButtonDto.fromList(self.readValue() as! [Any?])
    case 139:
      return MessageThemeDto.fromList(self.readValue() as! [Any?])
    case 140:
      return InAppMessageDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DyplinkLogLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DyplinkConfigDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? IdentifyParamsDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? IdentifyResultDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? DeepLinkResultDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? DeferredMatchResultDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? TrackConversionParamsDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BannerDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BannerCategoryDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? MessageButtonDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? MessageThemeDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? InAppMessageDto {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonApiPigeonCodecWriter(data: data)
  }
}

class PigeonApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonApiPigeonCodec(readerWriter: PigeonApiPigeonCodecReaderWriter())
}


/// Core SDK bridge — forwards to `com.dyplink.sdk.Dyplink`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DyplinkHostApi {
  /// Forwards to `Dyplink.init(context, DyplinkConfig)`. Idempotent.
  func init(config: DyplinkConfigDto) throws
  /// `Dyplink.isInitialized`.
  func isInitialized() throws -> Bool
  /// `Dyplink.distinctId`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd.
  func distinctId() throws -> String
  /// `Dyplink.deviceFingerprint`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd.
  func deviceFingerprint() throws -> String
  /// Forwards to suspend `Dyplink.identify(params)`.
  /// Throws `PlatformException` on any failure.
  func identify(params: IdentifyParamsDto, completion: @escaping (Result<IdentifyResultDto, Error>) -> Void)
  /// Forwards to `Dyplink.track(name, props)`. Fire-and-forget.
  func track(eventName: String, properties: [String?: Any?]?) throws
  /// Forwards to `Dyplink.trackConversion(params)`.
  func trackConversion(params: TrackConversionParamsDto) throws
  /// Forwards to `Dyplink.trackRevenue(amount, currency)`.
  func trackRevenue(amount: Double, currency: String) throws
  /// Forwards to suspend `Dyplink.matchDeferredDeepLink()`.
  func matchDeferredDeepLink(completion: @escaping (Result<DeferredMatchResultDto, Error>) -> Void)
  /// `Dyplink.getAttributedShortCode()`.
  func getAttributedShortCode() throws -> String?
  /// `Dyplink.getAttributedLinkId()`.
  func getAttributedLinkId() throws -> String?
  /// `Dyplink.reset()`.
  func reset() throws
  /// Forwards to suspend `Dyplink.flush()`.
  func flush(completion: @escaping (Result<Void, Error>) -> Void)
  func startDeepLinkStream() throws
  func stopDeepLinkStream() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DyplinkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `DyplinkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DyplinkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Forwards to `Dyplink.init(context, DyplinkConfig)`. Idempotent.
    let initChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.init\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! DyplinkConfigDto
        do {
          try api.init(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initChannel.setMessageHandler(nil)
    }
    /// `Dyplink.isInitialized`.
    let isInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.isInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isInitializedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isInitialized()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
    /// `Dyplink.distinctId`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd.
    let distinctIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.distinctId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      distinctIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.distinctId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      distinctIdChannel.setMessageHandler(nil)
    }
    /// `Dyplink.deviceFingerprint`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd.
    let deviceFingerprintChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.deviceFingerprint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deviceFingerprintChannel.setMessageHandler { _, reply in
        do {
          let result = try api.deviceFingerprint()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deviceFingerprintChannel.setMessageHandler(nil)
    }
    /// Forwards to suspend `Dyplink.identify(params)`.
    /// Throws `PlatformException` on any failure.
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! IdentifyParamsDto
        api.identify(params: paramsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    /// Forwards to `Dyplink.track(name, props)`. Fire-and-forget.
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventNameArg = args[0] as! String
        let propertiesArg: [String?: Any?]? = nilOrValue(args[1])
        do {
          try api.track(eventName: eventNameArg, properties: propertiesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    /// Forwards to `Dyplink.trackConversion(params)`.
    let trackConversionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.trackConversion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackConversionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! TrackConversionParamsDto
        do {
          try api.trackConversion(params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackConversionChannel.setMessageHandler(nil)
    }
    /// Forwards to `Dyplink.trackRevenue(amount, currency)`.
    let trackRevenueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.trackRevenue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackRevenueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let amountArg = args[0] as! Double
        let currencyArg = args[1] as! String
        do {
          try api.trackRevenue(amount: amountArg, currency: currencyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackRevenueChannel.setMessageHandler(nil)
    }
    /// Forwards to suspend `Dyplink.matchDeferredDeepLink()`.
    let matchDeferredDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.matchDeferredDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      matchDeferredDeepLinkChannel.setMessageHandler { _, reply in
        api.matchDeferredDeepLink { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      matchDeferredDeepLinkChannel.setMessageHandler(nil)
    }
    /// `Dyplink.getAttributedShortCode()`.
    let getAttributedShortCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.getAttributedShortCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAttributedShortCodeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAttributedShortCode()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAttributedShortCodeChannel.setMessageHandler(nil)
    }
    /// `Dyplink.getAttributedLinkId()`.
    let getAttributedLinkIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.getAttributedLinkId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAttributedLinkIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAttributedLinkId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAttributedLinkIdChannel.setMessageHandler(nil)
    }
    /// `Dyplink.reset()`.
    let resetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.reset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetChannel.setMessageHandler { _, reply in
        do {
          try api.reset()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetChannel.setMessageHandler(nil)
    }
    /// Forwards to suspend `Dyplink.flush()`.
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { _, reply in
        api.flush { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
    let startDeepLinkStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.startDeepLinkStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDeepLinkStreamChannel.setMessageHandler { _, reply in
        do {
          try api.startDeepLinkStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDeepLinkStreamChannel.setMessageHandler(nil)
    }
    let stopDeepLinkStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkHostApi.stopDeepLinkStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDeepLinkStreamChannel.setMessageHandler { _, reply in
        do {
          try api.stopDeepLinkStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDeepLinkStreamChannel.setMessageHandler(nil)
    }
  }
}
/// Push module bridge — forwards to `com.dyplink.push.DyplinkPush`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DyplinkPushHostApi {
  /// `DyplinkPush.init(context)`. Requires `DyplinkHostApi.init` first.
  func init() throws
  /// `DyplinkPush.isInitialized`.
  func isInitialized() throws -> Bool
  /// `DyplinkPush.isRegistered`.
  func isRegistered() throws -> Bool
  /// Forwards to suspend `DyplinkPush.registerToken(token)`.
  func registerToken(token: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Forwards to suspend `DyplinkPush.unregisterToken()`.
  func unregisterToken(completion: @escaping (Result<Void, Error>) -> Void)
  func startTokenStream() throws
  func stopTokenStream() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DyplinkPushHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `DyplinkPushHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DyplinkPushHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// `DyplinkPush.init(context)`. Requires `DyplinkHostApi.init` first.
    let initChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.init\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initChannel.setMessageHandler { _, reply in
        do {
          try api.init()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initChannel.setMessageHandler(nil)
    }
    /// `DyplinkPush.isInitialized`.
    let isInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.isInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isInitializedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isInitialized()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
    /// `DyplinkPush.isRegistered`.
    let isRegisteredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.isRegistered\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isRegisteredChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isRegistered()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isRegisteredChannel.setMessageHandler(nil)
    }
    /// Forwards to suspend `DyplinkPush.registerToken(token)`.
    let registerTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.registerToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.registerToken(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerTokenChannel.setMessageHandler(nil)
    }
    /// Forwards to suspend `DyplinkPush.unregisterToken()`.
    let unregisterTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.unregisterToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterTokenChannel.setMessageHandler { _, reply in
        api.unregisterToken { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unregisterTokenChannel.setMessageHandler(nil)
    }
    let startTokenStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.startTokenStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTokenStreamChannel.setMessageHandler { _, reply in
        do {
          try api.startTokenStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startTokenStreamChannel.setMessageHandler(nil)
    }
    let stopTokenStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.stopTokenStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopTokenStreamChannel.setMessageHandler { _, reply in
        do {
          try api.stopTokenStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopTokenStreamChannel.setMessageHandler(nil)
    }
  }
}
/// Banners module bridge — forwards to `com.dyplink.banners.DyplinkBanners`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DyplinkBannersHostApi {
  /// Forwards to suspend `DyplinkBanners.loadBanners(categoryId)`.
  func loadBanners(categoryId: String, completion: @escaping (Result<BannerCategoryDto, Error>) -> Void)
  /// `DyplinkBanners.clearCache()`.
  func clearCache() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DyplinkBannersHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `DyplinkBannersHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DyplinkBannersHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Forwards to suspend `DyplinkBanners.loadBanners(categoryId)`.
    let loadBannersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkBannersHostApi.loadBanners\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadBannersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let categoryIdArg = args[0] as! String
        api.loadBanners(categoryId: categoryIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadBannersChannel.setMessageHandler(nil)
    }
    /// `DyplinkBanners.clearCache()`.
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkBannersHostApi.clearCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { _, reply in
        do {
          try api.clearCache()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
  }
}
/// In-app messages bridge — forwards to `com.dyplink.messages.DyplinkMessages`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DyplinkMessagesHostApi {
  /// `DyplinkMessages.onAppOpen(context)`.
  func onAppOpen() throws
  /// `DyplinkMessages.onScreenView(context, screen)`.
  func onScreenView(screen: String) throws
  /// `DyplinkMessages.onEvent(context, event)`.
  func onEvent(event: String) throws
  func startMessageEventStream() throws
  func stopMessageEventStream() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DyplinkMessagesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `DyplinkMessagesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DyplinkMessagesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// `DyplinkMessages.onAppOpen(context)`.
    let onAppOpenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onAppOpen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAppOpenChannel.setMessageHandler { _, reply in
        do {
          try api.onAppOpen()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onAppOpenChannel.setMessageHandler(nil)
    }
    /// `DyplinkMessages.onScreenView(context, screen)`.
    let onScreenViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onScreenView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onScreenViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let screenArg = args[0] as! String
        do {
          try api.onScreenView(screen: screenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onScreenViewChannel.setMessageHandler(nil)
    }
    /// `DyplinkMessages.onEvent(context, event)`.
    let onEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventArg = args[0] as! String
        do {
          try api.onEvent(event: eventArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onEventChannel.setMessageHandler(nil)
    }
    let startMessageEventStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.startMessageEventStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startMessageEventStreamChannel.setMessageHandler { _, reply in
        do {
          try api.startMessageEventStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startMessageEventStreamChannel.setMessageHandler(nil)
    }
    let stopMessageEventStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.stopMessageEventStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMessageEventStreamChannel.setMessageHandler { _, reply in
        do {
          try api.stopMessageEventStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopMessageEventStreamChannel.setMessageHandler(nil)
    }
  }
}
