// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Mirrors com.dyplink.sdk.internal.util.LogLevel.
enum DyplinkLogLevel {
  none,
  error,
  warn,
  info,
  debug,
  verbose,
}

/// Flat configuration object passed to [DyplinkHostApi.init].
///
/// All fields have the same semantics as
/// `com.dyplink.sdk.DyplinkConfig.Builder`. The native side converts this
/// to a real `DyplinkConfig` via its builder so validation rules
/// (non-blank strings, positive intervals) are enforced by existing Kotlin
/// code.
class DyplinkConfigDto {
  DyplinkConfigDto({
    required this.baseUrl,
    required this.apiKey,
    required this.projectId,
    this.logLevel = DyplinkLogLevel.none,
    this.flushIntervalSeconds = 30,
    this.maxQueueSize = 1000,
    this.maxRetries = 3,
    this.sessionTimeoutSeconds = 300,
    this.enableAutoSessionTracking = true,
    this.enableAutoDeviceInfo = true,
    this.deepLinkHosts = const <String>[],
    this.customScheme,
  });

  String baseUrl;

  String apiKey;

  String projectId;

  DyplinkLogLevel logLevel;

  int flushIntervalSeconds;

  int maxQueueSize;

  int maxRetries;

  int sessionTimeoutSeconds;

  bool enableAutoSessionTracking;

  bool enableAutoDeviceInfo;

  List<String> deepLinkHosts;

  String? customScheme;

  Object encode() {
    return <Object?>[
      baseUrl,
      apiKey,
      projectId,
      logLevel,
      flushIntervalSeconds,
      maxQueueSize,
      maxRetries,
      sessionTimeoutSeconds,
      enableAutoSessionTracking,
      enableAutoDeviceInfo,
      deepLinkHosts,
      customScheme,
    ];
  }

  static DyplinkConfigDto decode(Object result) {
    result as List<Object?>;
    return DyplinkConfigDto(
      baseUrl: result[0]! as String,
      apiKey: result[1]! as String,
      projectId: result[2]! as String,
      logLevel: result[3]! as DyplinkLogLevel,
      flushIntervalSeconds: result[4]! as int,
      maxQueueSize: result[5]! as int,
      maxRetries: result[6]! as int,
      sessionTimeoutSeconds: result[7]! as int,
      enableAutoSessionTracking: result[8]! as bool,
      enableAutoDeviceInfo: result[9]! as bool,
      deepLinkHosts: (result[10] as List<Object?>?)!.cast<String>(),
      customScheme: result[11] as String?,
    );
  }
}

/// Mirrors com.dyplink.sdk.model.IdentifyParams — flat DTO (builder lives in Dart).
class IdentifyParamsDto {
  IdentifyParamsDto({
    this.distinctId,
    this.externalUserId,
    this.firstName,
    this.lastName,
    this.phone,
    this.avatar,
    this.locale,
    this.language,
    this.appVersion,
    this.appBuild,
    this.traits,
    this.utmSource,
    this.utmMedium,
    this.utmCampaign,
    this.utmContent,
    this.utmTerm,
    this.installSource,
    this.installCampaign,
    this.emailOptIn,
    this.smsOptIn,
    this.pushOptIn,
    this.gdprConsent,
    this.doNotTrack,
  });

  String? distinctId;

  String? externalUserId;

  String? firstName;

  String? lastName;

  String? phone;

  String? avatar;

  String? locale;

  String? language;

  String? appVersion;

  String? appBuild;

  Map<String?, Object?>? traits;

  String? utmSource;

  String? utmMedium;

  String? utmCampaign;

  String? utmContent;

  String? utmTerm;

  String? installSource;

  String? installCampaign;

  bool? emailOptIn;

  bool? smsOptIn;

  bool? pushOptIn;

  bool? gdprConsent;

  bool? doNotTrack;

  Object encode() {
    return <Object?>[
      distinctId,
      externalUserId,
      firstName,
      lastName,
      phone,
      avatar,
      locale,
      language,
      appVersion,
      appBuild,
      traits,
      utmSource,
      utmMedium,
      utmCampaign,
      utmContent,
      utmTerm,
      installSource,
      installCampaign,
      emailOptIn,
      smsOptIn,
      pushOptIn,
      gdprConsent,
      doNotTrack,
    ];
  }

  static IdentifyParamsDto decode(Object result) {
    result as List<Object?>;
    return IdentifyParamsDto(
      distinctId: result[0] as String?,
      externalUserId: result[1] as String?,
      firstName: result[2] as String?,
      lastName: result[3] as String?,
      phone: result[4] as String?,
      avatar: result[5] as String?,
      locale: result[6] as String?,
      language: result[7] as String?,
      appVersion: result[8] as String?,
      appBuild: result[9] as String?,
      traits: (result[10] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      utmSource: result[11] as String?,
      utmMedium: result[12] as String?,
      utmCampaign: result[13] as String?,
      utmContent: result[14] as String?,
      utmTerm: result[15] as String?,
      installSource: result[16] as String?,
      installCampaign: result[17] as String?,
      emailOptIn: result[18] as bool?,
      smsOptIn: result[19] as bool?,
      pushOptIn: result[20] as bool?,
      gdprConsent: result[21] as bool?,
      doNotTrack: result[22] as bool?,
    );
  }
}

/// Mirrors com.dyplink.sdk.model.IdentifyResult.
class IdentifyResultDto {
  IdentifyResultDto({
    required this.id,
    required this.projectId,
    this.distinctId,
    this.externalUserId,
    required this.deviceFingerprint,
    required this.platform,
  });

  String id;

  String projectId;

  String? distinctId;

  String? externalUserId;

  String deviceFingerprint;

  String platform;

  Object encode() {
    return <Object?>[
      id,
      projectId,
      distinctId,
      externalUserId,
      deviceFingerprint,
      platform,
    ];
  }

  static IdentifyResultDto decode(Object result) {
    result as List<Object?>;
    return IdentifyResultDto(
      id: result[0]! as String,
      projectId: result[1]! as String,
      distinctId: result[2] as String?,
      externalUserId: result[3] as String?,
      deviceFingerprint: result[4]! as String,
      platform: result[5]! as String,
    );
  }
}

/// Mirrors com.dyplink.sdk.model.DeepLinkResult.
class DeepLinkResultDto {
  DeepLinkResultDto({
    required this.url,
    this.shortCode,
    this.params,
    required this.isDeferred,
    this.linkId,
  });

  String url;

  String? shortCode;

  Map<String?, Object?>? params;

  bool isDeferred;

  String? linkId;

  Object encode() {
    return <Object?>[
      url,
      shortCode,
      params,
      isDeferred,
      linkId,
    ];
  }

  static DeepLinkResultDto decode(Object result) {
    result as List<Object?>;
    return DeepLinkResultDto(
      url: result[0]! as String,
      shortCode: result[1] as String?,
      params: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      isDeferred: result[3]! as bool,
      linkId: result[4] as String?,
    );
  }
}

/// Mirrors com.dyplink.sdk.model.DeferredMatchResult.
class DeferredMatchResultDto {
  DeferredMatchResultDto({
    required this.matched,
    this.linkId,
    this.shortCode,
    this.params,
  });

  bool matched;

  String? linkId;

  String? shortCode;

  Map<String?, Object?>? params;

  Object encode() {
    return <Object?>[
      matched,
      linkId,
      shortCode,
      params,
    ];
  }

  static DeferredMatchResultDto decode(Object result) {
    result as List<Object?>;
    return DeferredMatchResultDto(
      matched: result[0]! as bool,
      linkId: result[1] as String?,
      shortCode: result[2] as String?,
      params: (result[3] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

/// Mirrors com.dyplink.sdk.model.TrackConversionParams.
class TrackConversionParamsDto {
  TrackConversionParamsDto({
    required this.eventType,
    this.shortCode,
    this.linkId,
    this.externalUserId,
    this.metadata,
  });

  String eventType;

  String? shortCode;

  String? linkId;

  String? externalUserId;

  Map<String?, Object?>? metadata;

  Object encode() {
    return <Object?>[
      eventType,
      shortCode,
      linkId,
      externalUserId,
      metadata,
    ];
  }

  static TrackConversionParamsDto decode(Object result) {
    result as List<Object?>;
    return TrackConversionParamsDto(
      eventType: result[0]! as String,
      shortCode: result[1] as String?,
      linkId: result[2] as String?,
      externalUserId: result[3] as String?,
      metadata: (result[4] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

/// Mirrors com.dyplink.banners.model.Banner.
class BannerDto {
  BannerDto({
    required this.id,
    required this.title,
    this.imageUrl,
    this.clickUrl,
    this.ctaText,
    required this.sortOrder,
    required this.isActive,
    this.metadata,
  });

  String id;

  String title;

  String? imageUrl;

  String? clickUrl;

  String? ctaText;

  int sortOrder;

  bool isActive;

  Map<String?, Object?>? metadata;

  Object encode() {
    return <Object?>[
      id,
      title,
      imageUrl,
      clickUrl,
      ctaText,
      sortOrder,
      isActive,
      metadata,
    ];
  }

  static BannerDto decode(Object result) {
    result as List<Object?>;
    return BannerDto(
      id: result[0]! as String,
      title: result[1]! as String,
      imageUrl: result[2] as String?,
      clickUrl: result[3] as String?,
      ctaText: result[4] as String?,
      sortOrder: result[5]! as int,
      isActive: result[6]! as bool,
      metadata: (result[7] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

/// Mirrors com.dyplink.banners.model.BannerCategory.
class BannerCategoryDto {
  BannerCategoryDto({
    required this.id,
    required this.name,
    required this.layout,
    this.aspectRatio,
    required this.autoRotate,
    required this.rotationInterval,
    this.heading,
    required this.backgroundColor,
    required this.padding,
    required this.banners,
  });

  String id;

  String name;

  String layout;

  String? aspectRatio;

  bool autoRotate;

  int rotationInterval;

  String? heading;

  String backgroundColor;

  int padding;

  List<BannerDto?> banners;

  Object encode() {
    return <Object?>[
      id,
      name,
      layout,
      aspectRatio,
      autoRotate,
      rotationInterval,
      heading,
      backgroundColor,
      padding,
      banners,
    ];
  }

  static BannerCategoryDto decode(Object result) {
    result as List<Object?>;
    return BannerCategoryDto(
      id: result[0]! as String,
      name: result[1]! as String,
      layout: result[2]! as String,
      aspectRatio: result[3] as String?,
      autoRotate: result[4]! as bool,
      rotationInterval: result[5]! as int,
      heading: result[6] as String?,
      backgroundColor: result[7]! as String,
      padding: result[8]! as int,
      banners: (result[9] as List<Object?>?)!.cast<BannerDto?>(),
    );
  }
}

/// Mirrors com.dyplink.messages.model.MessageButton.
class MessageButtonDto {
  MessageButtonDto({
    required this.id,
    required this.text,
    required this.action,
    this.actionUrl,
    this.actionEvent,
    required this.style,
  });

  String id;

  String text;

  String action;

  String? actionUrl;

  String? actionEvent;

  String style;

  Object encode() {
    return <Object?>[
      id,
      text,
      action,
      actionUrl,
      actionEvent,
      style,
    ];
  }

  static MessageButtonDto decode(Object result) {
    result as List<Object?>;
    return MessageButtonDto(
      id: result[0]! as String,
      text: result[1]! as String,
      action: result[2]! as String,
      actionUrl: result[3] as String?,
      actionEvent: result[4] as String?,
      style: result[5]! as String,
    );
  }
}

/// Mirrors com.dyplink.messages.model.MessageTheme.
class MessageThemeDto {
  MessageThemeDto({
    this.backgroundColor,
    this.textColor,
    this.titleColor,
    this.buttonPrimaryColor,
    this.buttonSecondaryColor,
    this.overlayColor,
    this.borderRadius,
    this.animation,
  });

  String? backgroundColor;

  String? textColor;

  String? titleColor;

  String? buttonPrimaryColor;

  String? buttonSecondaryColor;

  String? overlayColor;

  int? borderRadius;

  String? animation;

  Object encode() {
    return <Object?>[
      backgroundColor,
      textColor,
      titleColor,
      buttonPrimaryColor,
      buttonSecondaryColor,
      overlayColor,
      borderRadius,
      animation,
    ];
  }

  static MessageThemeDto decode(Object result) {
    result as List<Object?>;
    return MessageThemeDto(
      backgroundColor: result[0] as String?,
      textColor: result[1] as String?,
      titleColor: result[2] as String?,
      buttonPrimaryColor: result[3] as String?,
      buttonSecondaryColor: result[4] as String?,
      overlayColor: result[5] as String?,
      borderRadius: result[6] as int?,
      animation: result[7] as String?,
    );
  }
}

/// Mirrors com.dyplink.messages.model.InAppMessage (delivered to the stream,
/// not returned from a method call).
class InAppMessageDto {
  InAppMessageDto({
    required this.id,
    required this.messageType,
    required this.title,
    this.body,
    this.imageUrl,
    required this.imagePosition,
    this.buttons,
    this.theme,
    required this.dismissOnTapOutside,
    this.autoDismissSeconds,
    required this.triggerDelay,
  });

  String id;

  String messageType;

  String title;

  String? body;

  String? imageUrl;

  String imagePosition;

  List<MessageButtonDto?>? buttons;

  MessageThemeDto? theme;

  bool dismissOnTapOutside;

  int? autoDismissSeconds;

  int triggerDelay;

  Object encode() {
    return <Object?>[
      id,
      messageType,
      title,
      body,
      imageUrl,
      imagePosition,
      buttons,
      theme,
      dismissOnTapOutside,
      autoDismissSeconds,
      triggerDelay,
    ];
  }

  static InAppMessageDto decode(Object result) {
    result as List<Object?>;
    return InAppMessageDto(
      id: result[0]! as String,
      messageType: result[1]! as String,
      title: result[2]! as String,
      body: result[3] as String?,
      imageUrl: result[4] as String?,
      imagePosition: result[5]! as String,
      buttons: (result[6] as List<Object?>?)?.cast<MessageButtonDto?>(),
      theme: result[7] as MessageThemeDto?,
      dismissOnTapOutside: result[8]! as bool,
      autoDismissSeconds: result[9] as int?,
      triggerDelay: result[10]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DyplinkLogLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is DyplinkConfigDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is IdentifyParamsDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is IdentifyResultDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is DeepLinkResultDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is DeferredMatchResultDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is TrackConversionParamsDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is BannerDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is BannerCategoryDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is MessageButtonDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is MessageThemeDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is InAppMessageDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DyplinkLogLevel.values[value];
      case 130: 
        return DyplinkConfigDto.decode(readValue(buffer)!);
      case 131: 
        return IdentifyParamsDto.decode(readValue(buffer)!);
      case 132: 
        return IdentifyResultDto.decode(readValue(buffer)!);
      case 133: 
        return DeepLinkResultDto.decode(readValue(buffer)!);
      case 134: 
        return DeferredMatchResultDto.decode(readValue(buffer)!);
      case 135: 
        return TrackConversionParamsDto.decode(readValue(buffer)!);
      case 136: 
        return BannerDto.decode(readValue(buffer)!);
      case 137: 
        return BannerCategoryDto.decode(readValue(buffer)!);
      case 138: 
        return MessageButtonDto.decode(readValue(buffer)!);
      case 139: 
        return MessageThemeDto.decode(readValue(buffer)!);
      case 140: 
        return InAppMessageDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Core SDK bridge — forwards to `com.dyplink.sdk.Dyplink`.
class DyplinkHostApi {
  /// Constructor for [DyplinkHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DyplinkHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Forwards to `Dyplink.init(context, DyplinkConfig)`. Idempotent.
  ///
  /// Named `initialize` (not `init`) because `init` is a Swift reserved
  /// keyword that Pigeon's Swift codegen can't escape correctly.
  Future<void> initialize(DyplinkConfigDto config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// `Dyplink.isInitialized`.
  Future<bool> isInitialized() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.isInitialized$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// `Dyplink.distinctId`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd.
  Future<String> distinctId() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.distinctId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// `Dyplink.deviceFingerprint`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd.
  Future<String> deviceFingerprint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.deviceFingerprint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Forwards to suspend `Dyplink.identify(params)`.
  /// Throws `PlatformException` on any failure.
  Future<IdentifyResultDto> identify(IdentifyParamsDto params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.identify$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as IdentifyResultDto?)!;
    }
  }

  /// Forwards to `Dyplink.track(name, props)`. Fire-and-forget.
  Future<void> track(String eventName, Map<String?, Object?>? properties) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.track$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[eventName, properties]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards to `Dyplink.trackConversion(params)`.
  Future<void> trackConversion(TrackConversionParamsDto params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.trackConversion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards to `Dyplink.trackRevenue(amount, currency)`.
  Future<void> trackRevenue(double amount, String currency) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.trackRevenue$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[amount, currency]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards to suspend `Dyplink.matchDeferredDeepLink()`.
  Future<DeferredMatchResultDto> matchDeferredDeepLink() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.matchDeferredDeepLink$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DeferredMatchResultDto?)!;
    }
  }

  /// `Dyplink.getAttributedShortCode()`.
  Future<String?> getAttributedShortCode() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.getAttributedShortCode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// `Dyplink.getAttributedLinkId()`.
  Future<String?> getAttributedLinkId() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.getAttributedLinkId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// `Dyplink.reset()`.
  Future<void> reset() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.reset$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards to suspend `Dyplink.flush()`.
  Future<void> flush() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.flush$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startDeepLinkStream() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.startDeepLinkStream$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopDeepLinkStream() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkHostApi.stopDeepLinkStream$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Push module bridge — forwards to `com.dyplink.push.DyplinkPush`.
class DyplinkPushHostApi {
  /// Constructor for [DyplinkPushHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DyplinkPushHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// `DyplinkPush.init(context)`. Requires `DyplinkHostApi.initialize` first.
  /// Named `initialize` (not `init`) — see [DyplinkHostApi.initialize] for why.
  Future<void> initialize() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// `DyplinkPush.isInitialized`.
  Future<bool> isInitialized() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.isInitialized$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// `DyplinkPush.isRegistered`.
  Future<bool> isRegistered() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.isRegistered$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Forwards to suspend `DyplinkPush.registerToken(token)`.
  Future<void> registerToken(String token) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.registerToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[token]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards to suspend `DyplinkPush.unregisterToken()`.
  Future<void> unregisterToken() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.unregisterToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startTokenStream() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.startTokenStream$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopTokenStream() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkPushHostApi.stopTokenStream$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Banners module bridge — forwards to `com.dyplink.banners.DyplinkBanners`.
class DyplinkBannersHostApi {
  /// Constructor for [DyplinkBannersHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DyplinkBannersHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Forwards to suspend `DyplinkBanners.loadBanners(categoryId)`.
  Future<BannerCategoryDto> loadBanners(String categoryId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkBannersHostApi.loadBanners$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[categoryId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BannerCategoryDto?)!;
    }
  }

  /// `DyplinkBanners.clearCache()`.
  Future<void> clearCache() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkBannersHostApi.clearCache$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// In-app messages bridge — forwards to `com.dyplink.messages.DyplinkMessages`.
class DyplinkMessagesHostApi {
  /// Constructor for [DyplinkMessagesHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DyplinkMessagesHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// `DyplinkMessages.onAppOpen(context)`.
  Future<void> onAppOpen() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onAppOpen$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// `DyplinkMessages.onScreenView(context, screen)`.
  Future<void> onScreenView(String screen) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onScreenView$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[screen]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// `DyplinkMessages.onEvent(context, event)`.
  Future<void> onEvent(String event) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onEvent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[event]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startMessageEventStream() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.startMessageEventStream$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopMessageEventStream() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.stopMessageEventStream$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
