// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.dyplink.dyplink

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Mirrors com.dyplink.sdk.internal.util.LogLevel. */
enum class DyplinkLogLevel(val raw: Int) {
  NONE(0),
  ERROR(1),
  WARN(2),
  INFO(3),
  DEBUG(4),
  VERBOSE(5);

  companion object {
    fun ofRaw(raw: Int): DyplinkLogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Flat configuration object passed to [DyplinkHostApi.init].
 *
 * All fields have the same semantics as
 * `com.dyplink.sdk.DyplinkConfig.Builder`. The native side converts this
 * to a real `DyplinkConfig` via its builder so validation rules
 * (non-blank strings, positive intervals) are enforced by existing Kotlin
 * code.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DyplinkConfigDto (
  val baseUrl: String,
  val apiKey: String,
  val projectId: String,
  val logLevel: DyplinkLogLevel,
  val flushIntervalSeconds: Long,
  val maxQueueSize: Long,
  val maxRetries: Long,
  val sessionTimeoutSeconds: Long,
  val enableAutoSessionTracking: Boolean,
  val enableAutoDeviceInfo: Boolean,
  val deepLinkHosts: List<String>,
  val customScheme: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DyplinkConfigDto {
      val baseUrl = pigeonVar_list[0] as String
      val apiKey = pigeonVar_list[1] as String
      val projectId = pigeonVar_list[2] as String
      val logLevel = pigeonVar_list[3] as DyplinkLogLevel
      val flushIntervalSeconds = pigeonVar_list[4] as Long
      val maxQueueSize = pigeonVar_list[5] as Long
      val maxRetries = pigeonVar_list[6] as Long
      val sessionTimeoutSeconds = pigeonVar_list[7] as Long
      val enableAutoSessionTracking = pigeonVar_list[8] as Boolean
      val enableAutoDeviceInfo = pigeonVar_list[9] as Boolean
      val deepLinkHosts = pigeonVar_list[10] as List<String>
      val customScheme = pigeonVar_list[11] as String?
      return DyplinkConfigDto(baseUrl, apiKey, projectId, logLevel, flushIntervalSeconds, maxQueueSize, maxRetries, sessionTimeoutSeconds, enableAutoSessionTracking, enableAutoDeviceInfo, deepLinkHosts, customScheme)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      baseUrl,
      apiKey,
      projectId,
      logLevel,
      flushIntervalSeconds,
      maxQueueSize,
      maxRetries,
      sessionTimeoutSeconds,
      enableAutoSessionTracking,
      enableAutoDeviceInfo,
      deepLinkHosts,
      customScheme,
    )
  }
}

/**
 * Mirrors com.dyplink.sdk.model.IdentifyParams — flat DTO (builder lives in Dart).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IdentifyParamsDto (
  val distinctId: String? = null,
  val externalUserId: String? = null,
  val firstName: String? = null,
  val lastName: String? = null,
  val phone: String? = null,
  val avatar: String? = null,
  val locale: String? = null,
  val language: String? = null,
  val appVersion: String? = null,
  val appBuild: String? = null,
  val traits: Map<String?, Any?>? = null,
  val utmSource: String? = null,
  val utmMedium: String? = null,
  val utmCampaign: String? = null,
  val utmContent: String? = null,
  val utmTerm: String? = null,
  val installSource: String? = null,
  val installCampaign: String? = null,
  val emailOptIn: Boolean? = null,
  val smsOptIn: Boolean? = null,
  val pushOptIn: Boolean? = null,
  val gdprConsent: Boolean? = null,
  val doNotTrack: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IdentifyParamsDto {
      val distinctId = pigeonVar_list[0] as String?
      val externalUserId = pigeonVar_list[1] as String?
      val firstName = pigeonVar_list[2] as String?
      val lastName = pigeonVar_list[3] as String?
      val phone = pigeonVar_list[4] as String?
      val avatar = pigeonVar_list[5] as String?
      val locale = pigeonVar_list[6] as String?
      val language = pigeonVar_list[7] as String?
      val appVersion = pigeonVar_list[8] as String?
      val appBuild = pigeonVar_list[9] as String?
      val traits = pigeonVar_list[10] as Map<String?, Any?>?
      val utmSource = pigeonVar_list[11] as String?
      val utmMedium = pigeonVar_list[12] as String?
      val utmCampaign = pigeonVar_list[13] as String?
      val utmContent = pigeonVar_list[14] as String?
      val utmTerm = pigeonVar_list[15] as String?
      val installSource = pigeonVar_list[16] as String?
      val installCampaign = pigeonVar_list[17] as String?
      val emailOptIn = pigeonVar_list[18] as Boolean?
      val smsOptIn = pigeonVar_list[19] as Boolean?
      val pushOptIn = pigeonVar_list[20] as Boolean?
      val gdprConsent = pigeonVar_list[21] as Boolean?
      val doNotTrack = pigeonVar_list[22] as Boolean?
      return IdentifyParamsDto(distinctId, externalUserId, firstName, lastName, phone, avatar, locale, language, appVersion, appBuild, traits, utmSource, utmMedium, utmCampaign, utmContent, utmTerm, installSource, installCampaign, emailOptIn, smsOptIn, pushOptIn, gdprConsent, doNotTrack)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      distinctId,
      externalUserId,
      firstName,
      lastName,
      phone,
      avatar,
      locale,
      language,
      appVersion,
      appBuild,
      traits,
      utmSource,
      utmMedium,
      utmCampaign,
      utmContent,
      utmTerm,
      installSource,
      installCampaign,
      emailOptIn,
      smsOptIn,
      pushOptIn,
      gdprConsent,
      doNotTrack,
    )
  }
}

/**
 * Mirrors com.dyplink.sdk.model.IdentifyResult.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IdentifyResultDto (
  val id: String,
  val projectId: String,
  val distinctId: String? = null,
  val externalUserId: String? = null,
  val deviceFingerprint: String,
  val platform: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IdentifyResultDto {
      val id = pigeonVar_list[0] as String
      val projectId = pigeonVar_list[1] as String
      val distinctId = pigeonVar_list[2] as String?
      val externalUserId = pigeonVar_list[3] as String?
      val deviceFingerprint = pigeonVar_list[4] as String
      val platform = pigeonVar_list[5] as String
      return IdentifyResultDto(id, projectId, distinctId, externalUserId, deviceFingerprint, platform)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      projectId,
      distinctId,
      externalUserId,
      deviceFingerprint,
      platform,
    )
  }
}

/**
 * Mirrors com.dyplink.sdk.model.DeepLinkResult.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeepLinkResultDto (
  val url: String,
  val shortCode: String? = null,
  val params: Map<String?, Any?>? = null,
  val isDeferred: Boolean,
  val linkId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeepLinkResultDto {
      val url = pigeonVar_list[0] as String
      val shortCode = pigeonVar_list[1] as String?
      val params = pigeonVar_list[2] as Map<String?, Any?>?
      val isDeferred = pigeonVar_list[3] as Boolean
      val linkId = pigeonVar_list[4] as String?
      return DeepLinkResultDto(url, shortCode, params, isDeferred, linkId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      shortCode,
      params,
      isDeferred,
      linkId,
    )
  }
}

/**
 * Mirrors com.dyplink.sdk.model.DeferredMatchResult.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeferredMatchResultDto (
  val matched: Boolean,
  val linkId: String? = null,
  val shortCode: String? = null,
  val params: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeferredMatchResultDto {
      val matched = pigeonVar_list[0] as Boolean
      val linkId = pigeonVar_list[1] as String?
      val shortCode = pigeonVar_list[2] as String?
      val params = pigeonVar_list[3] as Map<String?, Any?>?
      return DeferredMatchResultDto(matched, linkId, shortCode, params)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      matched,
      linkId,
      shortCode,
      params,
    )
  }
}

/**
 * Mirrors com.dyplink.sdk.model.TrackConversionParams.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TrackConversionParamsDto (
  val eventType: String,
  val shortCode: String? = null,
  val linkId: String? = null,
  val externalUserId: String? = null,
  val metadata: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackConversionParamsDto {
      val eventType = pigeonVar_list[0] as String
      val shortCode = pigeonVar_list[1] as String?
      val linkId = pigeonVar_list[2] as String?
      val externalUserId = pigeonVar_list[3] as String?
      val metadata = pigeonVar_list[4] as Map<String?, Any?>?
      return TrackConversionParamsDto(eventType, shortCode, linkId, externalUserId, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventType,
      shortCode,
      linkId,
      externalUserId,
      metadata,
    )
  }
}

/**
 * Mirrors com.dyplink.banners.model.Banner.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BannerDto (
  val id: String,
  val title: String,
  val imageUrl: String? = null,
  val clickUrl: String? = null,
  val ctaText: String? = null,
  val sortOrder: Long,
  val isActive: Boolean,
  val metadata: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerDto {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val imageUrl = pigeonVar_list[2] as String?
      val clickUrl = pigeonVar_list[3] as String?
      val ctaText = pigeonVar_list[4] as String?
      val sortOrder = pigeonVar_list[5] as Long
      val isActive = pigeonVar_list[6] as Boolean
      val metadata = pigeonVar_list[7] as Map<String?, Any?>?
      return BannerDto(id, title, imageUrl, clickUrl, ctaText, sortOrder, isActive, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      imageUrl,
      clickUrl,
      ctaText,
      sortOrder,
      isActive,
      metadata,
    )
  }
}

/**
 * Mirrors com.dyplink.banners.model.BannerCategory.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BannerCategoryDto (
  val id: String,
  val name: String,
  val layout: String,
  val aspectRatio: String? = null,
  val autoRotate: Boolean,
  val rotationInterval: Long,
  val heading: String? = null,
  val backgroundColor: String,
  val padding: Long,
  val banners: List<BannerDto?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerCategoryDto {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val layout = pigeonVar_list[2] as String
      val aspectRatio = pigeonVar_list[3] as String?
      val autoRotate = pigeonVar_list[4] as Boolean
      val rotationInterval = pigeonVar_list[5] as Long
      val heading = pigeonVar_list[6] as String?
      val backgroundColor = pigeonVar_list[7] as String
      val padding = pigeonVar_list[8] as Long
      val banners = pigeonVar_list[9] as List<BannerDto?>
      return BannerCategoryDto(id, name, layout, aspectRatio, autoRotate, rotationInterval, heading, backgroundColor, padding, banners)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      layout,
      aspectRatio,
      autoRotate,
      rotationInterval,
      heading,
      backgroundColor,
      padding,
      banners,
    )
  }
}

/**
 * Mirrors com.dyplink.messages.model.MessageButton.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MessageButtonDto (
  val id: String,
  val text: String,
  val action: String,
  val actionUrl: String? = null,
  val actionEvent: String? = null,
  val style: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageButtonDto {
      val id = pigeonVar_list[0] as String
      val text = pigeonVar_list[1] as String
      val action = pigeonVar_list[2] as String
      val actionUrl = pigeonVar_list[3] as String?
      val actionEvent = pigeonVar_list[4] as String?
      val style = pigeonVar_list[5] as String
      return MessageButtonDto(id, text, action, actionUrl, actionEvent, style)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      text,
      action,
      actionUrl,
      actionEvent,
      style,
    )
  }
}

/**
 * Mirrors com.dyplink.messages.model.MessageTheme.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MessageThemeDto (
  val backgroundColor: String? = null,
  val textColor: String? = null,
  val titleColor: String? = null,
  val buttonPrimaryColor: String? = null,
  val buttonSecondaryColor: String? = null,
  val overlayColor: String? = null,
  val borderRadius: Long? = null,
  val animation: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageThemeDto {
      val backgroundColor = pigeonVar_list[0] as String?
      val textColor = pigeonVar_list[1] as String?
      val titleColor = pigeonVar_list[2] as String?
      val buttonPrimaryColor = pigeonVar_list[3] as String?
      val buttonSecondaryColor = pigeonVar_list[4] as String?
      val overlayColor = pigeonVar_list[5] as String?
      val borderRadius = pigeonVar_list[6] as Long?
      val animation = pigeonVar_list[7] as String?
      return MessageThemeDto(backgroundColor, textColor, titleColor, buttonPrimaryColor, buttonSecondaryColor, overlayColor, borderRadius, animation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backgroundColor,
      textColor,
      titleColor,
      buttonPrimaryColor,
      buttonSecondaryColor,
      overlayColor,
      borderRadius,
      animation,
    )
  }
}

/**
 * Mirrors com.dyplink.messages.model.InAppMessage (delivered to the stream,
 * not returned from a method call).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InAppMessageDto (
  val id: String,
  val messageType: String,
  val title: String,
  val body: String? = null,
  val imageUrl: String? = null,
  val imagePosition: String,
  val buttons: List<MessageButtonDto?>? = null,
  val theme: MessageThemeDto? = null,
  val dismissOnTapOutside: Boolean,
  val autoDismissSeconds: Long? = null,
  val triggerDelay: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InAppMessageDto {
      val id = pigeonVar_list[0] as String
      val messageType = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val body = pigeonVar_list[3] as String?
      val imageUrl = pigeonVar_list[4] as String?
      val imagePosition = pigeonVar_list[5] as String
      val buttons = pigeonVar_list[6] as List<MessageButtonDto?>?
      val theme = pigeonVar_list[7] as MessageThemeDto?
      val dismissOnTapOutside = pigeonVar_list[8] as Boolean
      val autoDismissSeconds = pigeonVar_list[9] as Long?
      val triggerDelay = pigeonVar_list[10] as Long
      return InAppMessageDto(id, messageType, title, body, imageUrl, imagePosition, buttons, theme, dismissOnTapOutside, autoDismissSeconds, triggerDelay)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      messageType,
      title,
      body,
      imageUrl,
      imagePosition,
      buttons,
      theme,
      dismissOnTapOutside,
      autoDismissSeconds,
      triggerDelay,
    )
  }
}
private open class PigeonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DyplinkLogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DyplinkConfigDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IdentifyParamsDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IdentifyResultDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeepLinkResultDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeferredMatchResultDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackConversionParamsDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerCategoryDto.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageButtonDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageThemeDto.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InAppMessageDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DyplinkLogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is DyplinkConfigDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is IdentifyParamsDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is IdentifyResultDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DeepLinkResultDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is DeferredMatchResultDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is TrackConversionParamsDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BannerDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BannerCategoryDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is MessageButtonDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is MessageThemeDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is InAppMessageDto -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Core SDK bridge — forwards to `com.dyplink.sdk.Dyplink`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DyplinkHostApi {
  /** Forwards to `Dyplink.init(context, DyplinkConfig)`. Idempotent. */
  fun init(config: DyplinkConfigDto)
  /** `Dyplink.isInitialized`. */
  fun isInitialized(): Boolean
  /** `Dyplink.distinctId`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd. */
  fun distinctId(): String
  /** `Dyplink.deviceFingerprint`. Throws `PlatformException(NOT_INITIALIZED)` if not init'd. */
  fun deviceFingerprint(): String
  /**
   * Forwards to suspend `Dyplink.identify(params)`.
   * Throws `PlatformException` on any failure.
   */
  fun identify(params: IdentifyParamsDto, callback: (Result<IdentifyResultDto>) -> Unit)
  /** Forwards to `Dyplink.track(name, props)`. Fire-and-forget. */
  fun track(eventName: String, properties: Map<String?, Any?>?)
  /** Forwards to `Dyplink.trackConversion(params)`. */
  fun trackConversion(params: TrackConversionParamsDto)
  /** Forwards to `Dyplink.trackRevenue(amount, currency)`. */
  fun trackRevenue(amount: Double, currency: String)
  /** Forwards to suspend `Dyplink.matchDeferredDeepLink()`. */
  fun matchDeferredDeepLink(callback: (Result<DeferredMatchResultDto>) -> Unit)
  /** `Dyplink.getAttributedShortCode()`. */
  fun getAttributedShortCode(): String?
  /** `Dyplink.getAttributedLinkId()`. */
  fun getAttributedLinkId(): String?
  /** `Dyplink.reset()`. */
  fun reset()
  /** Forwards to suspend `Dyplink.flush()`. */
  fun flush(callback: (Result<Unit>) -> Unit)
  fun startDeepLinkStream()
  fun stopDeepLinkStream()

  companion object {
    /** The codec used by DyplinkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `DyplinkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DyplinkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.init$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as DyplinkConfigDto
            val wrapped: List<Any?> = try {
              api.init(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.isInitialized$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isInitialized())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.distinctId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.distinctId())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.deviceFingerprint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.deviceFingerprint())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as IdentifyParamsDto
            api.identify(paramsArg) { result: Result<IdentifyResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventNameArg = args[0] as String
            val propertiesArg = args[1] as Map<String?, Any?>?
            val wrapped: List<Any?> = try {
              api.track(eventNameArg, propertiesArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.trackConversion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as TrackConversionParamsDto
            val wrapped: List<Any?> = try {
              api.trackConversion(paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.trackRevenue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val amountArg = args[0] as Double
            val currencyArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.trackRevenue(amountArg, currencyArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.matchDeferredDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.matchDeferredDeepLink{ result: Result<DeferredMatchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.getAttributedShortCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAttributedShortCode())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.getAttributedLinkId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAttributedLinkId())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.reset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.reset()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flush{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.startDeepLinkStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startDeepLinkStream()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkHostApi.stopDeepLinkStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDeepLinkStream()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Push module bridge — forwards to `com.dyplink.push.DyplinkPush`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DyplinkPushHostApi {
  /** `DyplinkPush.init(context)`. Requires `DyplinkHostApi.init` first. */
  fun init()
  /** `DyplinkPush.isInitialized`. */
  fun isInitialized(): Boolean
  /** `DyplinkPush.isRegistered`. */
  fun isRegistered(): Boolean
  /** Forwards to suspend `DyplinkPush.registerToken(token)`. */
  fun registerToken(token: String, callback: (Result<Unit>) -> Unit)
  /** Forwards to suspend `DyplinkPush.unregisterToken()`. */
  fun unregisterToken(callback: (Result<Unit>) -> Unit)
  fun startTokenStream()
  fun stopTokenStream()

  companion object {
    /** The codec used by DyplinkPushHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `DyplinkPushHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DyplinkPushHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.init$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.init()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.isInitialized$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isInitialized())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.isRegistered$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isRegistered())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.registerToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.registerToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.unregisterToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unregisterToken{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.startTokenStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startTokenStream()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkPushHostApi.stopTokenStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopTokenStream()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Banners module bridge — forwards to `com.dyplink.banners.DyplinkBanners`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DyplinkBannersHostApi {
  /** Forwards to suspend `DyplinkBanners.loadBanners(categoryId)`. */
  fun loadBanners(categoryId: String, callback: (Result<BannerCategoryDto>) -> Unit)
  /** `DyplinkBanners.clearCache()`. */
  fun clearCache()

  companion object {
    /** The codec used by DyplinkBannersHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `DyplinkBannersHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DyplinkBannersHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkBannersHostApi.loadBanners$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val categoryIdArg = args[0] as String
            api.loadBanners(categoryIdArg) { result: Result<BannerCategoryDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkBannersHostApi.clearCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearCache()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * In-app messages bridge — forwards to `com.dyplink.messages.DyplinkMessages`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DyplinkMessagesHostApi {
  /** `DyplinkMessages.onAppOpen(context)`. */
  fun onAppOpen()
  /** `DyplinkMessages.onScreenView(context, screen)`. */
  fun onScreenView(screen: String)
  /** `DyplinkMessages.onEvent(context, event)`. */
  fun onEvent(event: String)
  fun startMessageEventStream()
  fun stopMessageEventStream()

  companion object {
    /** The codec used by DyplinkMessagesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `DyplinkMessagesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DyplinkMessagesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onAppOpen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.onAppOpen()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onScreenView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val screenArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.onScreenView(screenArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.onEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.onEvent(eventArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.startMessageEventStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startMessageEventStream()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dyplink.DyplinkMessagesHostApi.stopMessageEventStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopMessageEventStream()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
